run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 50
  exclude-rules:
    - path: _bench_test\.go
      linters:
        - unused

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - misspell
    - gocyclo
    - revive
    - staticcheck
    - unused
    - errcheck
    - nolintlint

linters-settings:
  gocyclo:
    min-complexity: 55
  revive:
    rules:
      - name: exported
      - name: package-comments
  nolintlint:
    require-explanation: true
    require-specific: true
